spring.application.name=ecommerceusb
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_usb_db
spring.datasource.username=ecommerce_usb_usr
spring.datasource.password=ecommerce_usb_pwd
spring.datasource.driver-class-name=org.postgresql.Driver
